# Generated by Django 5.2.3 on 2025-07-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bathroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='view_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
