# Generated by Django 5.2.3 on 2025-07-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_order_id_booking_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
